name: electro_magnetism_solver
description: "A Flutter project that assists students to solve Electromagnetism questions."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  flutter:
    sdk: flutter

  equations: ^5.0.2
  cupertino_icons: ^1.0.6
  math_expressions: ^2.6.0
  flutter_math_fork: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
